/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:07:34 GMT 2025
 */

package org.apache.commons.codec.binary;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.codec.binary.Base64;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Base64_ESTest extends Base64_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Base64 base64_0 = null;
      try {
        base64_0 = new Base64(false);
       //  fail("Expecting exception: IllegalArgumentException");
       // Unstable assertion
      } catch(IllegalArgumentException e) {
         //
         // lineSeperator must not contain base64 characters: [A
         // ]
         //
         verifyException("org.apache.commons.codec.binary.Base64", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = new byte[70];
      Base64 base64_0 = new Base64(4, byteArray0, false);
      base64_0.encode(byteArray0, 12, 4);
      base64_0.encode(byteArray0, 4, 26);
      base64_0.encode(byteArray0, 19, 26);
      base64_0.encode(byteArray0, 26, 19);
      base64_0.encode(byteArray0, 26, 19);
      base64_0.encode(byteArray0, 4, 62);
      base64_0.encode(byteArray0, 12, 51);
      base64_0.encode(byteArray0, 4, 62);
      base64_0.encode(byteArray0, 4, 62);
      assertFalse(base64_0.isUrlSafe());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Base64 base64_0 = null;
      try {
        base64_0 = new Base64(true);
       //  fail("Expecting exception: IllegalArgumentException");
       // Unstable assertion
      } catch(IllegalArgumentException e) {
         //
         // lineSeperator must not contain base64 characters: [A
         // ]
         //
         verifyException("org.apache.commons.codec.binary.Base64", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Base64 base64_0 = null;
      try {
        base64_0 = new Base64();
       //  fail("Expecting exception: IllegalArgumentException");
       // Unstable assertion
      } catch(IllegalArgumentException e) {
         //
         // lineSeperator must not contain base64 characters: [A
         // ]
         //
         verifyException("org.apache.commons.codec.binary.Base64", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      byte[] byteArray0 = new byte[70];
      Base64 base64_0 = new Base64(4, byteArray0, false);
      base64_0.encode(byteArray0, 27, 12);
      base64_0.encode(byteArray0, 12, 4);
      base64_0.encode(byteArray0, 4, 12);
      base64_0.encode(byteArray0, 22, 27);
      base64_0.encode(byteArray0, 19, 27);
      base64_0.encode(byteArray0, 19, 19);
      base64_0.encode(byteArray0, 27, 19);
      base64_0.encode(byteArray0, 27, 19);
      base64_0.encode(byteArray0, 4, 62);
      base64_0.encode(byteArray0, 12, 51);
      base64_0.encode(byteArray0, 4, 62);
      base64_0.encode(byteArray0, 15, 4);
      base64_0.encode(byteArray0, 4, 12);
      base64_0.encode(byteArray0, 19, (-1));
      assertFalse(base64_0.isUrlSafe());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      byte[] byteArray0 = new byte[40];
      Base64 base64_0 = new Base64(2, byteArray0, false);
      base64_0.encode(byteArray0, 2, (-568));
      base64_0.encode(byteArray0, (-3647), 1919);
      assertFalse(base64_0.isUrlSafe());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      byte[] byteArray0 = new byte[40];
      Base64 base64_0 = new Base64(2, byteArray0, false);
      base64_0.encode(byteArray0, 4, 17);
      base64_0.encode(byteArray0, 2, (-568));
      assertFalse(base64_0.isUrlSafe());
  }
}
