/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Mar 11 11:10:19 GMT 2025
 */

package org.apache.commons.math.optimization.fitting;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class GaussianFitter_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.math.optimization.fitting.GaussianFitter"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/Users/yanglin/Documents/Projects/as-gen-integration/outputs/evosuite_outputs/Math_58"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/5r/68kjfs5d3lngb74f6mhp88jh0000gn/T/"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(GaussianFitter_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.math.optimization.fitting.GaussianFitter$1",
      "org.apache.commons.math.exception.NumberIsTooSmallException",
      "org.apache.commons.math.analysis.MultivariateVectorialFunction",
      "org.apache.commons.math.analysis.function.Gaussian$Parametric",
      "org.apache.commons.math.exception.MathRuntimeException",
      "org.apache.commons.math.exception.MathIllegalArgumentException",
      "org.apache.commons.math.exception.NullArgumentException",
      "org.apache.commons.math.optimization.fitting.WeightedObservedPoint",
      "org.apache.commons.math.optimization.fitting.CurveFitter",
      "org.apache.commons.math.analysis.ParametricUnivariateRealFunction",
      "org.apache.commons.math.optimization.DifferentiableMultivariateVectorialOptimizer",
      "org.apache.commons.math.optimization.fitting.CurveFitter$TheoreticalValuesFunction",
      "org.apache.commons.math.optimization.BaseMultivariateVectorialOptimizer",
      "org.apache.commons.math.optimization.fitting.GaussianFitter",
      "org.apache.commons.math.exception.DimensionMismatchException",
      "org.apache.commons.math.exception.NotStrictlyPositiveException",
      "org.apache.commons.math.exception.MathIllegalNumberException",
      "org.apache.commons.math.exception.MathThrowable",
      "org.apache.commons.math.analysis.MultivariateMatrixFunction",
      "org.apache.commons.math.optimization.BaseOptimizer",
      "org.apache.commons.math.analysis.DifferentiableMultivariateVectorialFunction"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(GaussianFitter_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.math.optimization.fitting.CurveFitter",
      "org.apache.commons.math.optimization.fitting.GaussianFitter",
      "org.apache.commons.math.optimization.fitting.GaussianFitter$1",
      "org.apache.commons.math.optimization.fitting.GaussianFitter$ParameterGuesser",
      "org.apache.commons.math.optimization.fitting.GaussianFitter$ParameterGuesser$1",
      "org.apache.commons.math.linear.AbstractRealMatrix",
      "org.apache.commons.math.linear.BlockRealMatrix",
      "org.apache.commons.math.exception.MathRuntimeException",
      "org.apache.commons.math.exception.MathIllegalArgumentException",
      "org.apache.commons.math.exception.MathIllegalNumberException",
      "org.apache.commons.math.exception.NumberIsTooSmallException",
      "org.apache.commons.math.exception.NotStrictlyPositiveException",
      "org.apache.commons.math.exception.util.LocalizedFormats",
      "org.apache.commons.math.exception.util.ArgUtils",
      "org.apache.commons.math.optimization.fitting.WeightedObservedPoint",
      "org.apache.commons.math.random.BitsStreamGenerator",
      "org.apache.commons.math.random.AbstractWell",
      "org.apache.commons.math.random.Well19937a",
      "org.apache.commons.math.random.GaussianRandomGenerator",
      "org.apache.commons.math.random.UncorrelatedRandomVectorGenerator",
      "org.apache.commons.math.linear.Array2DRowRealMatrix",
      "org.apache.commons.math.exception.NoDataException",
      "org.apache.commons.math.random.MersenneTwister",
      "org.apache.commons.math.util.FastMath",
      "org.apache.commons.math.optimization.BaseMultiStartMultivariateVectorialOptimizer",
      "org.apache.commons.math.optimization.MultiStartDifferentiableMultivariateVectorialOptimizer",
      "org.apache.commons.math.exception.NullArgumentException",
      "org.apache.commons.math.random.Well19937c",
      "org.apache.commons.math.random.UnitSphereRandomVectorGenerator",
      "org.apache.commons.math.random.Well512a",
      "org.apache.commons.math.analysis.function.Gaussian$Parametric",
      "org.apache.commons.math.optimization.fitting.CurveFitter$TheoreticalValuesFunction",
      "org.apache.commons.math.random.CorrelatedRandomVectorGenerator",
      "org.apache.commons.math.linear.MatrixUtils",
      "org.apache.commons.math.random.Well44497a",
      "org.apache.commons.math.exception.DimensionMismatchException",
      "org.apache.commons.math.optimization.BaseMultiStartMultivariateVectorialOptimizer$1",
      "org.apache.commons.math.random.Well1024a",
      "org.apache.commons.math.random.UniformRandomGenerator",
      "org.apache.commons.math.random.Well44497b"
    );
  }
}
