/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:29:37 GMT 2025
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.io.Writer;
import org.apache.commons.lang3.text.translate.LookupTranslator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LookupTranslator_ESTest extends LookupTranslator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[1][7];
      CharSequence[] charSequenceArray1 = new CharSequence[2];
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn(970, 970).when(charSequence0).length();
      doReturn((CharSequence) null).when(charSequence0).subSequence(anyInt() , anyInt());
      doReturn("").when(charSequence0).toString();
      charSequenceArray1[0] = charSequence0;
      charSequenceArray1[1] = charSequence0;
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      // Undeclared exception!
      try { 
        lookupTranslator0.translate(charSequence0, (-1), (Writer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.text.translate.LookupTranslator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LookupTranslator lookupTranslator0 = new LookupTranslator((CharSequence[][]) null);
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn(0, 0).when(charSequence0).length();
      StringWriter stringWriter0 = new StringWriter();
      int int0 = lookupTranslator0.translate(charSequence0, 7, (Writer) stringWriter0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CharSequence[] charSequenceArray0 = new CharSequence[2];
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn((-1512)).when(charSequence0).length();
      doReturn("The Writer must not be null").when(charSequence0).toString();
      charSequenceArray0[0] = charSequence0;
      CharSequence[][] charSequenceArray1 = new CharSequence[1][9];
      charSequenceArray1[0] = charSequenceArray0;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray1);
      // Undeclared exception!
      try { 
        lookupTranslator0.translate((CharSequence) "The Writer must not be null", 9, (Writer) null);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }
}
