/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:27:18 GMT 2025
 */

package org.apache.commons.math.util;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.math.util.MathUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MathUtils_ESTest extends MathUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = MathUtils.gcd(1160, 1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = MathUtils.gcd((-2826), (-2826));
      assertEquals(2826, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = MathUtils.gcd(49, 0);
      assertEquals(49, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = MathUtils.gcd(0, 0);
      assertEquals(0, int0);
  }
}
