/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:43:48 GMT 2025
 */

package org.apache.commons.math.complex;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.math.complex.Complex;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Complex_ESTest extends Complex_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Complex complex0 = new Complex(4059.4337576259, 4059.4337576259);
      Complex complex1 = Complex.INF;
      Complex complex2 = complex0.divide(complex1);
      assertEquals(0.7853981633974483, complex0.getArgument(), 0.01);
      assertEquals(0.0, complex2.abs(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Complex complex0 = Complex.I;
      Complex complex1 = complex0.divide(complex0);
      assertEquals(1.0, complex1.abs(), 0.01);
      assertEquals(0.0, complex1.getArgument(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Complex complex0 = Complex.ONE;
      Complex complex1 = Complex.ZERO;
      Complex complex2 = complex0.divide(complex1);
      assertEquals(Double.NaN, complex2.getArgument(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Complex complex0 = Complex.NaN;
      Complex complex1 = Complex.INF;
      Complex complex2 = complex0.INF.divide(complex1);
      assertEquals(0.7853981633974483, complex1.getArgument(), 0.01);
      assertFalse(complex2.isInfinite());
      assertNotSame(complex2, complex0);
      assertTrue(complex2.isNaN());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Complex complex0 = Complex.NaN;
      complex0.divide(complex0);
  }
}
