/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:06:17 GMT 2025
 */

package org.apache.commons.lang.time;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.time.DurationFormatUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DurationFormatUtils_ESTest extends DurationFormatUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = DurationFormatUtils.formatPeriod((-1L), (-3919L), "))hA+[B;Ws-Z V");
      assertNotNull(string0);
  }
}
