/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:37:51 GMT 2025
 */

package org.apache.commons.math.complex;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.math.complex.Complex;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Complex_ESTest extends Complex_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Complex complex0 = new Complex(486.4255262, 486.4255262);
      Complex complex1 = complex0.tan();
      assertEquals(0.0, complex1.getReal(), 0.01);
      assertEquals(0.7853981633974483, complex0.getArgument(), 0.01);
      assertEquals(1.0, complex1.abs(), 0.01);
      assertEquals(1.5707963267948966, complex1.getArgument(), 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Complex complex0 = new Complex(0.0, (-1135.56));
      Complex complex1 = complex0.NaN.tan();
      assertEquals(1135.56, complex0.abs(), 0.01);
      assertEquals(0.0, complex0.getReal(), 0.01);
      assertEquals((-1135.56), complex0.getImaginary(), 0.01);
      assertEquals(Double.NaN, complex1.getReal(), 0.01);
  }
}
