/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:10:02 GMT 2025
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Element;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Element_ESTest extends Element_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Element element0 = new Element("D)+OMd1S[Pao%n[^");
      // Undeclared exception!
      try { 
        element0.selectFirst("D)+OMd1S[Pao%n[^");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Could not parse query 'D)+OMd1S[Pao%n[^': unexpected token at ')+OMd1S[Pao%n[^'
         //
         verifyException("org.jsoup.select.QueryParser", e);
      }
  }
}
