/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:43:58 GMT 2025
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.cli.Util;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Util_ESTest extends Util_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = Util.stripLeadingAndTrailingQuotes("\"D/?<\"");
      assertEquals("D/?<", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = Util.stripLeadingAndTrailingQuotes("\"W\"qe<u:");
      assertEquals("\"W\"qe<u:", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = Util.stripLeadingAndTrailingQuotes("]{-k_");
      assertEquals("]{-k_", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = Util.stripLeadingAndTrailingQuotes("\"D/?<\"\"");
      assertEquals("\"D/?<\"\"", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = Util.stripLeadingAndTrailingQuotes("%");
      assertEquals("%", string0);
  }
}
