/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:21:05 GMT 2025
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Document;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Element_ESTest extends Element_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Document document0 = new Document("{uh<$mI~)EAj%/0");
      // Undeclared exception!
      try { 
        document0.select("{uh<$mI~)EAj%/0");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Could not parse query '{uh<$mI~)EAj%/0': unexpected token at '{uh<$mI~)EAj%/0'
         //
         verifyException("org.jsoup.select.QueryParser", e);
      }
  }
}
