/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:21:00 GMT 2025
 */

package org.apache.commons.math.stat.correlation;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.math.linear.OpenMapRealMatrix;
import org.apache.commons.math.linear.RealMatrix;
import org.apache.commons.math.stat.correlation.PearsonsCorrelation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PearsonsCorrelation_ESTest extends PearsonsCorrelation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OpenMapRealMatrix openMapRealMatrix0 = new OpenMapRealMatrix(12, 12);
      PearsonsCorrelation pearsonsCorrelation0 = new PearsonsCorrelation(openMapRealMatrix0, 752);
      RealMatrix realMatrix0 = pearsonsCorrelation0.getCorrelationPValues();
      assertEquals(12, realMatrix0.getColumnDimension());
      assertEquals(Double.NaN, realMatrix0.getFrobeniusNorm(), 0.01);
  }
}
