/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:41:16 GMT 2025
 */

package org.apache.commons.math3.fitting;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math3.fitting.PolynomialFitter;
import org.apache.commons.math3.optim.nonlinear.vector.jacobian.LevenbergMarquardtOptimizer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PolynomialFitter_ESTest extends PolynomialFitter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LevenbergMarquardtOptimizer levenbergMarquardtOptimizer0 = new LevenbergMarquardtOptimizer(2806.45509, 2806.45509, 2806.45509, 2.2204E-16, 2806.45509);
      PolynomialFitter polynomialFitter0 = new PolynomialFitter(levenbergMarquardtOptimizer0);
      double[] doubleArray0 = new double[0];
      // Undeclared exception!
      try { 
        polynomialFitter0.fit((-501), doubleArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // -501 is smaller than, or equal to, the minimum (0)
         //
         verifyException("org.apache.commons.math3.optim.MaxEval", e);
      }
  }
}
