/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:16:22 GMT 2025
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.WordUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WordUtils_ESTest extends WordUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = WordUtils.abbreviate("_&2ma[ U]I> ", (-1203), 1622, "");
      assertEquals("_&2ma[", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = WordUtils.abbreviate("r9Q9DXmb c=fJ0tB", (-2240), 0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = WordUtils.abbreviate("S7M7bRI^HAv{P2P", 2, (-339), "S7M7bRI^HAv{P2P");
      assertEquals("S7S7M7bRI^HAv{P2P", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = WordUtils.abbreviate("52]J`PB!W", 1607, (-1), "WDkkni_rD#");
      assertEquals("52]J`PB!W", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = WordUtils.abbreviate("", 57, 0, "Caught a SecurityException reading the system property '");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = WordUtils.abbreviate((String) null, 316, 1622, (String) null);
      assertNull(string0);
  }
}
