/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:10:22 GMT 2025
 */

package org.apache.commons.math3.distribution;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.math3.distribution.NormalDistribution;
import org.apache.commons.math3.random.Well44497a;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NormalDistribution_ESTest extends NormalDistribution_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Well44497a well44497a0 = new Well44497a(4499201580859392L);
      NormalDistribution normalDistribution0 = new NormalDistribution(well44497a0, 4499201580859392L, 997.32575374394, 997.32575374394);
      double double0 = normalDistribution0.density(4499201580859392L);
      assertEquals(4.0001201102429345E-4, double0, 0.01);
  }
}
