/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:12:47 GMT 2025
 */

package org.apache.commons.math.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math.util.MathUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MathUtils_ESTest extends MathUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      long long0 = MathUtils.binomialCoefficient(67, (-2150));
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      long long0 = MathUtils.binomialCoefficient(62, 9);
      assertEquals(20286591270L, long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        MathUtils.binomialCoefficient(1906, 1201);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // overflow: multiply
         //
         verifyException("org.apache.commons.math.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      long long0 = MathUtils.binomialCoefficient(9, 8);
      assertEquals(9L, long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      long long0 = MathUtils.binomialCoefficient(40, 1);
      assertEquals(40L, long0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      long long0 = MathUtils.binomialCoefficient(13, 0);
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      long long0 = MathUtils.binomialCoefficient(9, 9);
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        MathUtils.binomialCoefficient((-2991), (-2991));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // must have n >= 0 for binomial coefficient (n,k)
         //
         verifyException("org.apache.commons.math.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      // Undeclared exception!
      try { 
        MathUtils.binomialCoefficient(67, 1101);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // must have n >= k for binomial coefficient (n,k)
         //
         verifyException("org.apache.commons.math.util.MathUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      long long0 = MathUtils.binomialCoefficient(52, 9);
      assertEquals(3679075400L, long0);
  }
}
