/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:41:19 GMT 2025
 */

package org.joda.time.format;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.joda.time.format.ISOPeriodFormat;
import org.joda.time.format.PeriodFormatter;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ISOPeriodFormat_ESTest extends ISOPeriodFormat_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ISOPeriodFormat.standard();
      PeriodFormatter periodFormatter0 = ISOPeriodFormat.standard();
      assertTrue(periodFormatter0.isParser());
  }
}
