/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:42:31 GMT 2025
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.io.Writer;
import org.apache.commons.lang3.text.translate.NumericEntityUnescaper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NumericEntityUnescaper_ESTest extends NumericEntityUnescaper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NumericEntityUnescaper numericEntityUnescaper0 = new NumericEntityUnescaper();
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn('&', '#', 'X', 'X', '#').when(charSequence0).charAt(anyInt());
      StringWriter stringWriter0 = new StringWriter();
      // Undeclared exception!
      numericEntityUnescaper0.translate(charSequence0, (-5), (Writer) stringWriter0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NumericEntityUnescaper numericEntityUnescaper0 = new NumericEntityUnescaper();
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn('&', '&').when(charSequence0).charAt(anyInt());
      StringWriter stringWriter0 = new StringWriter();
      int int0 = numericEntityUnescaper0.translate(charSequence0, (int) '&', (Writer) stringWriter0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NumericEntityUnescaper numericEntityUnescaper0 = new NumericEntityUnescaper();
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn("4").when(charSequence0).toString();
      CharSequence charSequence1 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn('&', '#', '#', '&', ';').when(charSequence1).charAt(anyInt());
      doReturn(charSequence0).when(charSequence1).subSequence(anyInt() , anyInt());
      StringWriter stringWriter0 = new StringWriter();
      int int0 = numericEntityUnescaper0.translate(charSequence1, (int) '&', (Writer) stringWriter0);
      assertEquals("\u0004", stringWriter0.toString());
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NumericEntityUnescaper numericEntityUnescaper0 = new NumericEntityUnescaper();
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn('a').when(charSequence0).charAt(anyInt());
      int int0 = numericEntityUnescaper0.translate(charSequence0, 87, (Writer) null);
      assertEquals(0, int0);
  }
}
