/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 11 11:07:26 GMT 2025
 */

package org.apache.commons.compress.archivers.jar;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.DataOutputStream;
import java.util.jar.JarEntry;
import java.util.zip.ZipEntry;
import org.apache.commons.compress.archivers.jar.JarArchiveEntry;
import org.apache.commons.compress.archivers.jar.JarArchiveOutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JarArchiveOutputStream_ESTest extends JarArchiveOutputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("org.apache.commons.compress.archivers.jar.JarArchiveEntry");
      DataOutputStream dataOutputStream0 = new DataOutputStream(mockFileOutputStream0);
      JarArchiveOutputStream jarArchiveOutputStream0 = new JarArchiveOutputStream(dataOutputStream0);
      JarEntry jarEntry0 = new JarEntry("K");
      JarArchiveEntry jarArchiveEntry0 = new JarArchiveEntry((ZipEntry) jarEntry0);
      jarArchiveOutputStream0.putArchiveEntry(jarArchiveEntry0);
      jarArchiveOutputStream0.putArchiveEntry(jarArchiveEntry0);
      assertFalse(jarArchiveEntry0.isDirectory());
  }
}
